FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS dotnet_restore
WORKDIR /app
COPY "Esbc.sln" "Esbc.sln"
COPY "__tests__/EsbcProducer/EsbcProducer.csproj" "__tests__/EsbcProducer/EsbcProducer.csproj"
COPY "src/EsbcProducer/EsbcProducer.csproj" "src/EsbcProducer/EsbcProducer.csproj"
RUN dotnet restore --packages ./pkg "Esbc.sln"
RUN COPY . .
RUN dotnet test
RUN dotnet publish -c Release -o dist
ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_URLS=http://+:80
ENTRYPOINT ["dotnet", "./dist/EsbcProducer.dll"]

# COPY --from=dotnet_code /app/idle.sh .
# ENTRYPOINT ["sh","/app/idle.sh"]


