version: "3.3"

volumes:
  zoodata:
  zoodatalog:
  kfkdata:
  rmq:
  rmqdata:
  rmqlog:

networks:
  esbc_net:

services:
  esbc_producer:
    build:
      context: ../
      dockerfile: ./docker/producer.dockerfile
    networks:
      - esbc_net
    environment:
      - QueueConfiguration__HostName=rabbitmq
      - QueueConfiguration__Port=5672
      - QueueConfiguration__User=admin
      - QueueConfiguration__Password=admin
      - QueueConfiguration__QueueMechanism=RabbitMq
      - QueueConfiguration__KafkaConfiguration__RequestTimeoutMs=5000
    ports:
      - 5000:80
    depends_on:
      - kafka1
      - rabbitmq

  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    networks:
      - esbc_net
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - zoodata:/data
      - zoodatalog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:5.5.0
    hostname: kafka1
    ports:
      - "9092:9092"
    networks:
      - esbc_net
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - kfkdata:/var/lib/kafka/data
    depends_on:
      - zoo1

  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    container_name: rabbitmq
    networks:
      - esbc_net
    volumes:
      - rmq:/etc/rabbitmq/
      - rmqdata:/var/lib/rabbitmq/
      - rmqlog:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: "cookie_frase_secret_long_enough_i_guess_maybe_loooong"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    ports:
      - 8080:5672
      - 15672:15672
      - 25676:25676
